[client]
showErrorDetails = false

[browser]
gatherUsageStats = false

[theme]
# base = ""
primaryColor = "purple"
backgroundColor = "lightgray"
secondaryBackgroundColor = "lightblue"
# textColor = ""
# font = ""

[ui]
hideTopBar = true

[logger]
level = "error"
