# Environment Variables
export DB_NAME="db"
export MACHINE_TYPE="e2-micro"
export REGION="us-west1"
export ZONE="us-west1-a"
export BOOT_DISK_SIZE="30"
export TAGS="db"
export FIREWALL_RULES_NAME="ports"
export STATIC_IP_ADDRESS_NAME="db-static-ip-address"
export CLOUD_BUILD_REGION="us-west2"
export APP_ARTIFACT_NAME="app"
export APP_NAME="app"
export APP_VERSION="latest"
export APP_SERVICE_ACCOUNT_NAME='app-service-account'
echo "#----------Exporting Environment Variables is done.----------#"